services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Pacific/Auckland
    volumes:
      - homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

  matter-hub:
    container_name: matter-hub
    image: ghcr.io/riddix/home-assistant-matter-hub:latest
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Pacific/Auckland
      HAMH_HOME_ASSISTANT_URL: ${HOME_ASSISTANT_URL}
      HAMH_HOME_ASSISTANT_ACCESS_TOKEN: ${HOME_ASSISTANT_ACCESS_TOKEN}
      HAMH_LOG_LEVEL: info
      HAMH_HTTP_PORT: 8482
    volumes:
      - matter-hub:/data

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    environment:
      TZ: Pacific/Auckland
    ports:
      - 3080:8080
    volumes:
      - zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto:/mosquitto/config
      - mosquitto:/mosquitto/data
      - mosquitto:/mosquitto/log

  airconnect:
    container_name: airconnect
    image: 1activegeek/airconnect
    restart: always
    network_mode: host
    environment:
      AIRCAST_VAR: -x /config/config.xml
      AIRUPNP_VAR: kill
    volumes:
      - airconnect:/config

volumes:
  homeassistant:
  airconnect:
  matter-hub:
  matterbridge:
  zigbee2mqtt:
  mosquitto:
