---
version: 2.1

# Setup default propreties we want on all/most containers
x-default-container &default-container:
  user: 1000:1000
  group_add: 
    - "109"
  environment:
    - PUID=1000 
    - PGID=100 
    - TZ=Africa/Casablanca 
  restart: unless-stopped

# containers on the mediarr nework, also have access to specific volumes
x-mediarr-container &mediarr-container:
  <<: *default-container
  networks:
    - mediarr
  volumes: 
    - myMedia:/mnt/media 

services: 
  jellyfin: 
    <<: *mediarr-container
    container_name: jellyfin 
    image: lscr.io/linuxserver/jellyfin:latest
    hostname: jellyfin 
    volumes: 
      - ./configs/jellyfin:/config 
    ports: 
      - 8096:8096 
      - 8920:8920
    devices: 
      - /dev/dri/renderD128:/dev/dri/renderD128 

  bazarr: 
    <<: *mediarr-container
    image: lscr.io/linuxserver/bazarr:latest 
    container_name: bazarr 
    hostname: bazarr 
    volumes: 
      - ./configs/mediarr/bazarr:/config 
    ports: 
      - 6767:6767
    depends_on: 
      - sonarr 
      - radarr 

  jellyseerr: 
    <<: *mediarr-container
    image: fallenbagel/jellyseerr:latest 
    container_name: jellyseerr 
    hostname: jellyseerr 
    ports: 
      - 5055:5055 
    volumes: 
      - ./configs/mediarr/jellyseerr:/app/config 
    depends_on: 
      - sonarr 
      - radarr 

  tdarr: 
    <<: *mediarr-container
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr 
    hostname: tdarr 
    volumes: 
      - ./configs/mediarr/tdarr:/config 
    ports: 
      - 8265:8265 
      - 8266:8266
    depends_on: 
      - jellyfin

  prowlarr: 
    <<: *mediarr-container
    image: linuxserver/prowlarr:latest 
    container_name: prowlarr 
    hostname: prowlarr 
    volumes: 
      - ./configs/mediarr/prowlarr:/config 
    ports: 
      - 9696:9696 
    depends_on: 
      - flaresolverr 

  flaresolverr: 
    <<: *mediarr-container
    image: ghcr.io/flaresolverr/flaresolverr:latest 
    container_name: flaresolverr 
    hostname: flaresolverr 
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info} 
      - LOG_HTML=${LOG_HTML:-false} 
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none} 
    restart: unless-stopped 

  qbittorrent: 
    <<: *mediarr-container
    image: lscr.io/linuxserver/qbittorrent:latest 
    container_name: qbittorrent 
    hostname: qbittorrent 
    environment:
      - WEBUI_PORT=8080 
    volumes: 
      - ./configs/mediarr/qbittorrent:/config
    ports: 
      - 8080:8080 
      - 6881:6881 
      - 6881:6881/udp 

  radarr: 
    <<: *mediarr-container
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr 
    hostname: radarr 
    volumes: 
      - ./configs/mediarr/radarr:/config
    ports: 
      - 7878:7878 
    depends_on: 
      - prowlarr 
      - qbittorrent 
      - jellyfin 

  sonarr: 
    <<: *mediarr-container
    image: lscr.io/linuxserver/sonarr:latest 
    container_name: sonarr 
    hostname: sonarr
    volumes: 
      - ./configs/mediarr/sonarr:/config 
    depends_on: 
      - prowlarr 
      - qbittorrent 
      - jellyfin 
    ports: 
      - 8989:8989 

networks: 
  firefox: 
    driver: bridge 
  duplicati: 
    driver: bridge 
  mediarr: 
    driver: bridge

volumes:
  myMedia:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/media
