services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Pacific/Auckland
    ports:
      - 8096:8096
    volumes:
      - jellyfin:/config
      - /mnt/media:/media
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Pacific/Auckland
    ports:
      - 5055:5055
    volumes:
      - jellyseerr:/app/config

volumes:
  jellyfin:
  jellyseerr:
