services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Pacific/Auckland
    ports:
      - 8096:8096
    volumes:
      - jellyfin:/config
      - /mnt/media:/media
    devices:
      - /dev/dri:/dev/dri

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Pacific/Auckland
    ports:
      - 5055:5055
    volumes:
      - jellyseerr:/app/config

volumes:
  jellyfin:
  jellyseerr:
