services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /docker/jellyfin:/config
      - /mnt/media:/media
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /docker/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
