services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    network_mode: host
    restart: always
    volumes:
      - homebridge:/homebridge

  airconnect:
    container_name: airconnect
    image: 1activegeek/airconnect
    network_mode: host
    restart: always
    volumes:
      - airconnect:/config
    environment:
      - AIRCAST_VAR=-x /config/config.xml
      - AIRUPNP_VAR=kill

volumes:
  homebridge:
  airconnect:
